remote_theme: "simonarnell/jekyll-theme-basically-basic"
lang: en-GB
title:	Simon Arnell's Site
description:	A site where I can blog and people can find my CV
url: https://simonarnell.github.io
author:
  name: Simon Arnell
  twitter: simonarnell
social:
  name: Simon Arnell
  links:
    - https://twitter.com/simonarnell
    - https://www.facebook.com/simon.arnell
    - https://www.linkedin.com/in/simonarnell
    - https://github.com/simonarnell
    - https://www.crunchbase.com/person/simon-arnell
    - https://scholar.google.co.uk/citations?user=aN7Yn_cAAAAJ
logo:	/assets/images/0.jpg
twitter_username:	simonarnell
github_username:	simonarnell
linkedin_username: simonarnell
facebook_username: simon.arnell
google_analytics: UA-127874216-1
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
disqus:
  shortname: simonarnell-github
